//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_4_0 /Fo BasicHLSL.o /Fc BasicHLSL.asm BasicHLSL.hlsl /E
//    RenderScenePS /Gec /Zi
//
//
// Buffer Definitions: 
//
// cbuffer $Params
// {
//
//   bool bTexture;                     // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// MeshTextureSampler                sampler      NA          NA    0        1
// MeshTextureSampler                texture  float4          2d    0        1
// $Params                           cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float       
// COLOR                    0   xyzw        1     NONE  float   xyzw
// TEXCOORD                 0   xy          2     NONE  float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Target                0   xyzw        0   TARGET  float   xyzw
//
ps_4_0
dcl_constantbuffer cb0[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xy
dcl_output o0.xyzw
dcl_temps 1

#line 111 "C:\Users\Tim Jones\Documents\GitHub\slimshader\src\SlimShader.Tests\Shaders\Sdk\Direct3D11\BasicHLSL11\BasicHLSL.hlsl"
if_nz cb0[0].x
  sample r0.xyzw, v2.xyxx, t0.xyzw, s0
  mul o0.xyzw, r0.xyzw, v1.xyzw  // Output<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
else 

#line 114
  mov o0.xyzw, v1.xyzw  // Output<0,1,2,3>

#line 111
endif 

#line 116
ret 
// Approximately 7 instruction slots used
