//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20714
//
//
///
// Buffer Definitions: 
//
// cbuffer cbMultiPerFrameFrame
// {
//
//   float4x4 mWorldViewProj;           // Offset:    0 Size:    64 [unused]
//   float4x4 mWorldView;               // Offset:   64 Size:    64 [unused]
//   float4x4 mWorld;                   // Offset:  128 Size:    64
//   float4x4 mView;                    // Offset:  192 Size:    64 [unused]
//   float4x4 mProj;                    // Offset:  256 Size:    64 [unused]
//   float3 vEye;                       // Offset:  320 Size:    12 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// cbMultiPerFrameFrame              cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float       
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_4_0
dcl_constantbuffer cb0[12], immediateIndexed
dcl_input v0.xyzw
dcl_input v2.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dp4 o0.x, v0.xyzw, cb0[8].xyzw
dp4 o0.y, v0.xyzw, cb0[9].xyzw
dp4 o0.z, v0.xyzw, cb0[10].xyzw
dp4 o0.w, v0.xyzw, cb0[11].xyzw
mov o1.xy, v2.xyxx
ret 
// Approximately 6 instruction slots used
