//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20714
//
//
///
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// PictureSampler                    sampler      NA          NA    0        1
// PictureSamplerComparison        sampler_c      NA          NA    1        1
// Picture                           texture  float4          2d    0        1
// PictureMS                         texture  float4      2dMS32    1        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2dms(32) (float,float,float,float) t1
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 2
resinfo_indexable(texture2d)(float,float,float,float) r0.zw, l(1), t0.zwxy
lod r0.x, v1.xyxx, t0.x, s0
lod r0.y, v1.xyxx, t0.y, s0
gather4_aoffimmi_indexable(0,1,0)(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t0.xyzw, s0.x
add r0.xyzw, r0.xyzw, r1.xyzw
samplepos r1.xy, t1.xyxx, l(0)
mov r1.zw, l(0,0,0,0)
add r0.xyzw, r0.xyzw, r1.xyzw
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t0.xyzw, s0
add r0.xyzw, r0.xyzw, r1.xyzw
sample_b_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t0.xyzw, s0, l(0.500000)
add r0.xyzw, r0.xyzw, r1.xyzw
sample_c_indexable(texture2d)(float,float,float,float) r1.x, v1.xyxx, t0.xxxx, s1, l(0.400000)
add r0.xyzw, r0.xyzw, r1.xxxx
sample_c_lz_indexable(texture2d)(float,float,float,float) r1.x, v1.xyxx, t0.xxxx, s1, l(0.600000)
add r0.xyzw, r0.xyzw, r1.xxxx
sample_d_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t0.xyzw, s0, l(0.100000, 0.100000, 0.000000, 0.000000), l(0.200000, 0.200000, 0.000000, 0.000000)
add r0.xyzw, r0.xyzw, r1.xyzw
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t0.xyzw, s0, l(1.500000)
add o0.xyzw, r0.xyzw, r1.xyzw
ret 
// Approximately 21 instruction slots used
