//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
//
///
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input v0.xyz
dcl_output o0.xyzw
mov o0.xyz, v0.xyzx
mov o0.w, l(1.000000)
ret 
// Approximately 3 instruction slots used
