//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
//
///
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   float4 g_MaterialAmbientColor;     // Offset:    0 Size:    16
//   float4 g_MaterialDiffuseColor;     // Offset:   16 Size:    16
//   int g_nNumLights;                  // Offset:   32 Size:     4 [unused]
//   float3 g_LightDir;                 // Offset:   36 Size:    12
//   float4 g_LightDiffuse;             // Offset:   48 Size:    16
//   float4 g_LightAmbient;             // Offset:   64 Size:    16
//   float g_fTime;                     // Offset:   80 Size:     4 [unused]
//   float4x4 g_mWorld;                 // Offset:   96 Size:    64
//   float4x4 g_mWorldViewProjection;   // Offset:  160 Size:    64
//
// }
//
// cbuffer $Params
// {
//
//   int nNumLights;                    // Offset:    0 Size:     4
//   bool bTexture;                     // Offset:    4 Size:     4
//   bool bAnimate;                     // Offset:    8 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
// $Params                           cbuffer      NA          NA    1        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
vs_4_0
dcl_constantbuffer cb0[14], immediateIndexed
dcl_constantbuffer cb1[1], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xyz
dcl_input v2.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output o2.xy
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- vPos.x; v0.y <- vPos.y; v0.z <- vPos.z; v0.w <- vPos.w; 
//   v1.x <- vNormal.x; v1.y <- vNormal.y; v1.z <- vNormal.z; 
//   v2.x <- vTexCoord0.x; v2.y <- vTexCoord0.y; 
//   o2.x <- <RenderSceneVS return value>.TextureUV.x; o2.y <- <RenderSceneVS return value>.TextureUV.y; 
//   o1.x <- <RenderSceneVS return value>.Diffuse.x; o1.y <- <RenderSceneVS return value>.Diffuse.y; o1.z <- <RenderSceneVS return value>.Diffuse.z; o1.w <- <RenderSceneVS return value>.Diffuse.w; 
//   o0.x <- <RenderSceneVS return value>.Position.x; o0.y <- <RenderSceneVS return value>.Position.y; o0.z <- <RenderSceneVS return value>.Position.z; o0.w <- <RenderSceneVS return value>.Position.w
//
#line 68 "C:\Users\Tim Jones\Documents\GitHub\slimshader\shaders\Sdk\Direct3D11\BasicHLSL11\BasicHLSL.fx"
dp4 o0.x, v0.xyzw, cb0[10].xyzw
dp4 o0.y, v0.xyzw, cb0[11].xyzw
dp4 o0.z, v0.xyzw, cb0[12].xyzw
dp4 o0.w, v0.xyzw, cb0[13].xyzw

#line 71
dp3 r0.x, v1.xyzx, cb0[6].xyzx
dp3 r0.y, v1.xyzx, cb0[7].xyzx
dp3 r0.z, v1.xyzx, cb0[8].xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.wwww, r0.xyzx  // r0.x <- vNormalWorldSpace.x; r0.y <- vNormalWorldSpace.y; r0.z <- vNormalWorldSpace.z

#line 76
dp3 r0.x, r0.xyzx, cb0[2].yzwy
max r0.x, r0.x, l(0.000000)
mov r0.yzw, l(0,0,0,0)  // r0.y <- vTotalLightDiffuse.x; r0.z <- vTotalLightDiffuse.y; r0.w <- vTotalLightDiffuse.z
mov r1.x, l(0)  // r1.x <- i
loop 
  ige r1.y, r1.x, cb1[0].x
  breakc_nz r1.y
  mad r0.yzw, cb0[3].xxyz, r0.xxxx, r0.yyzw
  iadd r1.x, r1.x, l(1)
endloop 
mul r1.xyz, cb0[0].xyzx, cb0[4].xyzx
mad o1.xyz, cb0[1].xyzx, r0.yzwy, r1.xyzx

#line 86
movc o2.xy, cb1[0].yyyy, v2.xyxx, l(0,0,0,0)
mov o1.w, l(1.000000)
ret 
// Approximately 25 instruction slots used
