//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_4_0 /Fo SimpleBezier11.o /Fc SimpleBezier11.asm
//    SimpleBezier11.hlsl /E BezierVS
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyz         0     NONE  float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyz         0     NONE  float   xyz 
//
vs_4_0
dcl_input v0.xyz
dcl_output o0.xyz
mov o0.xyz, v0.xyzx
ret 
// Approximately 2 instruction slots used
