//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20714
//
//
///
// Buffer Definitions: 
//
// cbuffer cbPNTriangles
// {
//
//   float4x4 g_f4x4World;              // Offset:    0 Size:    64 [unused]
//   float4x4 g_f4x4ViewProjection;     // Offset:   64 Size:    64
//   float4x4 g_f4x4WorldViewProjection;// Offset:  128 Size:    64 [unused]
//   float4 g_f4LightDir;               // Offset:  192 Size:    16
//   float4 g_f4Eye;                    // Offset:  208 Size:    16 [unused]
//   float4 g_f4ViewVector;             // Offset:  224 Size:    16 [unused]
//   float4 g_f4TessFactors;            // Offset:  240 Size:    16 [unused]
//   float4 g_f4ScreenParams;           // Offset:  256 Size:    16 [unused]
//   float4 g_f4GUIParams1;             // Offset:  272 Size:    16 [unused]
//   float4 g_f4GUIParams2;             // Offset:  288 Size:    16 [unused]
//   float4 g_f4ViewFrustumPlanes[4];   // Offset:  304 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// cbPNTriangles                     cbuffer      NA          NA    0        1
//
//
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TessFactor            0   x           0  TRIEDGE   float       
// POSITION                 3    yzw        0     NONE   float    yzw
// SV_TessFactor            1   x           1  TRIEDGE   float       
// POSITION                 4    yzw        1     NONE   float    yzw
// SV_TessFactor            2   x           2  TRIEDGE   float       
// POSITION                 5    yzw        2     NONE   float    yzw
// SV_InsideTessFactor      0   x           3   TRIINT   float       
// POSITION                 6    yzw        3     NONE   float    yzw
// POSITION                 7   xyz         4     NONE   float   xyz 
// POSITION                 8   xyz         5     NONE   float   xyz 
// CENTER                   0   xyz         6     NONE   float   xyz 
// NORMAL                   3   xyz         7     NONE   float   xyz 
// NORMAL                   4   xyz         8     NONE   float   xyz 
// NORMAL                   5   xyz         9     NONE   float   xyz 
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// COLOR                    0   xyzw        2     NONE   float   xyzw
//
// Tessellation Domain   # of control points
// -------------------- --------------------
// Triangle                                3
//
ds_5_0
dcl_input_control_point_count 3
dcl_tessellator_domain domain_tri
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[13], immediateIndexed
dcl_input vpc0.yzw
dcl_input vpc1.yzw
dcl_input vpc2.yzw
dcl_input vpc3.yzw
dcl_input vpc4.xyz
dcl_input vpc5.xyz
dcl_input vpc6.xyz
dcl_input vpc7.xyz
dcl_input vpc8.xyz
dcl_input vpc9.xyz
dcl_input vDomain.xyz
dcl_input vicp[3][0].xyz
dcl_input vicp[3][1].xyz
dcl_input vicp[3][2].xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_output o2.xyzw
dcl_temps 5
mul r0.xyz, vpc1.yzwy, vDomain.zzzz
mul r1.xyz, vDomain.xyzx, vDomain.xyzx
mul r2.xyz, r1.xxxx, vicp[1][0].xyzx
mul r2.xyz, r2.xyzx, vDomain.xxxx
mul r3.xyz, r1.zzzz, vicp[0][0].xyzx
mad r2.xyz, r3.xyzx, vDomain.zzzz, r2.xyzx
mul r3.xyz, r1.yyyy, vicp[2][0].xyzx
mad r2.xyz, r3.xyzx, vDomain.yyyy, r2.xyzx
mul r3.xyz, r1.xyzx, l(3.000000, 3.000000, 3.000000, 0.000000)
mul r4.xyz, r3.zzzz, vpc0.yzwy
mad r2.xyz, r4.xyzx, vDomain.xxxx, r2.xyzx
mad r0.xyz, r0.xyzx, r3.xxxx, r2.xyzx
mul r2.xyz, r3.zzzz, vpc5.xyzx
mad r0.xyz, r2.xyzx, vDomain.yyyy, r0.xyzx
mul r2.xyz, r3.xxxx, vpc2.yzwy
mad r0.xyz, r2.xyzx, vDomain.yyyy, r0.xyzx
mul r2.xyz, vpc4.xyzx, vDomain.zzzz
mad r0.xyz, r2.xyzx, r3.yyyy, r0.xyzx
mul r2.xyz, vpc3.yzwy, vDomain.xxxx
mad r0.xyz, r2.xyzx, r3.yyyy, r0.xyzx
mul r2.xyz, vpc6.xyzx, vDomain.zzzz
mul r2.xyz, r2.xyzx, vDomain.xxxx
mul r2.xyz, r2.xyzx, vDomain.yyyy
mad r0.xyz, r2.xyzx, l(6.000000, 6.000000, 6.000000, 0.000000), r0.xyzx
mov r0.w, l(1.000000)
dp4 o0.x, r0.xyzw, cb0[4].xyzw
dp4 o0.y, r0.xyzw, cb0[5].xyzw
dp4 o0.z, r0.xyzw, cb0[6].xyzw
dp4 o0.w, r0.xyzw, cb0[7].xyzw
mul r0.xy, vDomain.xxxx, vicp[1][2].xyxx
mad r0.xy, vicp[0][2].xyxx, vDomain.zzzz, r0.xyxx
mad o1.xy, vicp[2][2].xyxx, vDomain.yyyy, r0.xyxx
mul r0.xyz, r1.xxxx, vicp[1][1].xyzx
mad r0.xyz, vicp[0][1].xyzx, r1.zzzz, r0.xyzx
mad r0.xyz, vicp[2][1].xyzx, r1.yyyy, r0.xyzx
mul r1.xyz, vpc7.xyzx, vDomain.zzzz
mad r0.xyz, r1.xyzx, vDomain.xxxx, r0.xyzx
mul r1.xyz, vpc8.xyzx, vDomain.xxxx
mad r0.xyz, r1.xyzx, vDomain.yyyy, r0.xyzx
mul r1.xyz, vpc9.xyzx, vDomain.zzzz
mad r0.xyz, r1.xyzx, vDomain.yyyy, r0.xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.wwww, r0.xyzx
dp3 r0.x, r0.xyzx, cb0[12].xyzx
max r0.x, r0.x, l(0.000000)
add o2.xyz, r0.xxxx, l(0.200000, 0.200000, 0.200000, 0.000000)
mov o2.w, l(1.000000)
ret 
// Approximately 49 instruction slots used
