//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20714
//
//
///
// Buffer Definitions: 
//
// cbuffer cbPNTriangles
// {
//
//   float4x4 g_f4x4World;              // Offset:    0 Size:    64
//   float4x4 g_f4x4ViewProjection;     // Offset:   64 Size:    64 [unused]
//   float4x4 g_f4x4WorldViewProjection;// Offset:  128 Size:    64
//   float4 g_f4LightDir;               // Offset:  192 Size:    16
//   float4 g_f4Eye;                    // Offset:  208 Size:    16 [unused]
//   float4 g_f4ViewVector;             // Offset:  224 Size:    16 [unused]
//   float4 g_f4TessFactors;            // Offset:  240 Size:    16 [unused]
//   float4 g_f4ScreenParams;           // Offset:  256 Size:    16 [unused]
//   float4 g_f4GUIParams1;             // Offset:  272 Size:    16 [unused]
//   float4 g_f4GUIParams2;             // Offset:  288 Size:    16 [unused]
//   float4 g_f4ViewFrustumPlanes[4];   // Offset:  304 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// cbPNTriangles                     cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// COLOR                    0   xyzw        2     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[13], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xyz
dcl_input v2.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_output o2.xyzw
dcl_temps 1
mov r0.xyz, v0.xyzx
mov r0.w, l(1.000000)
dp4 o0.x, r0.xyzw, cb0[8].xyzw
dp4 o0.y, r0.xyzw, cb0[9].xyzw
dp4 o0.z, r0.xyzw, cb0[10].xyzw
dp4 o0.w, r0.xyzw, cb0[11].xyzw
mov o1.xy, v2.xyxx
dp3 r0.x, v1.xyzx, cb0[0].xyzx
dp3 r0.y, v1.xyzx, cb0[1].xyzx
dp3 r0.z, v1.xyzx, cb0[2].xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.wwww, r0.xyzx
dp3 r0.x, r0.xyzx, cb0[12].xyzx
max r0.x, r0.x, l(0.000000)
add o2.xyz, r0.xxxx, l(0.200000, 0.200000, 0.200000, 0.000000)
mov o2.w, l(1.000000)
ret 
// Approximately 18 instruction slots used
