//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T cs_4_0 /Fo NBodyGravityCS11.o /Fc NBodyGravityCS11.asm
//    NBodyGravityCS11.hlsl /E CSMain
//
//
// Buffer Definitions: 
//
// cbuffer cbCS
// {
//
//   uint4 g_param;                     // Offset:    0 Size:    16
//   float4 g_paramf;                   // Offset:   16 Size:    16
//
// }
//
// Resource bind info for oldPosVelo
// {
//
//   struct
//   {
//       
//       float4 pos;                    // Offset:    0
//       float4 velo;                   // Offset:   16
//
//   } $Element;                        // Offset:    0 Size:    32
//
// }
//
// Resource bind info for newPosVelo
// {
//
//   struct
//   {
//       
//       float4 pos;                    // Offset:    0
//       float4 velo;                   // Offset:   16
//
//   } $Element;                        // Offset:    0 Size:    32
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// oldPosVelo                        texture  struct         r/o    0        1
// newPosVelo                            UAV  struct         r/w    0        1
// cbCS                              cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
cs_4_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[2], immediateIndexed
dcl_resource_structured t0, 32 
dcl_uav_structured u0, 32
dcl_input vThreadIDInGroupFlattened
dcl_input vThreadID.x
dcl_temps 4
dcl_tgsm_structured g0, 16, 128
dcl_thread_group 128, 1, 1
ld_structured r0.xyzw, vThreadID.x, l(0), t0.xyzw
mov r1.xyzw, l(0,0,0,0)
loop 
  uge r2.x, r1.w, cb0[0].y
  breakc_nz r2.x
  ishl r2.x, r1.w, l(7)
  iadd r2.x, r2.x, vThreadIDInGroupFlattened.x
  ld_structured r2.xyz, r2.x, l(0), t0.xyzx
  store_structured g0.xyz, vThreadIDInGroupFlattened.x, l(0), r2.xyzx
  sync_g_t
  ld_structured r2.xyz, l(0), l(0), g0.xyzx
  add r2.xyz, -r0.xyzx, r2.xyzx
  dp3 r2.w, r2.xyzx, r2.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.x, r2.w, r2.w
  mul r2.w, r2.w, r3.x
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r2.xyzx, r2.wwww, r1.xyzx
  ld_structured r3.xyz, l(1), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(2), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(3), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(4), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(5), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(6), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(7), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(8), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(9), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(10), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(11), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(12), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(13), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(14), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(15), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(16), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(17), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(18), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(19), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(20), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(21), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(22), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(23), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(24), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(25), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(26), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(27), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(28), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(29), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(30), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(31), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(32), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(33), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(34), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(35), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(36), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(37), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(38), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(39), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(40), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(41), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(42), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(43), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(44), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(45), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(46), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(47), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(48), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(49), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(50), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(51), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(52), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(53), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(54), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(55), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(56), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(57), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(58), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(59), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(60), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(61), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(62), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(63), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(64), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(65), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(66), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(67), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(68), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(69), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(70), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(71), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(72), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(73), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(74), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(75), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(76), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(77), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(78), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(79), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(80), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(81), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(82), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(83), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(84), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(85), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(86), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(87), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(88), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(89), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(90), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(91), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(92), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(93), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(94), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(95), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(96), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(97), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(98), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(99), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(100), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(101), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(102), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(103), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(104), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(105), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(106), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(107), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(108), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(109), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(110), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(111), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(112), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(113), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(114), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(115), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(116), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(117), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(118), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(119), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(120), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(121), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(122), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(123), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(124), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(125), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(126), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r2.xyz, r3.xyzx, r2.wwww, r2.xyzx
  ld_structured r3.xyz, l(127), l(0), g0.xyzx
  add r3.xyz, -r0.xyzx, r3.xyzx
  dp3 r2.w, r3.xyzx, r3.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.w, r2.w, r2.w
  mul r2.w, r2.w, r3.w
  mul r2.w, r2.w, l(66.730003)
  mad r1.xyz, r3.xyzx, r2.wwww, r2.xyzx
  sync_g_t
  iadd r1.w, r1.w, l(1)
endloop 
ult r1.w, vThreadID.x, cb0[0].x
if_nz r1.w
  ld_structured r2.xyz, vThreadID.x, l(16), t0.xyzx
  ishl r1.w, cb0[0].y, l(7)
  iadd r1.w, -r1.w, cb0[0].x
  dp3 r2.w, -r0.xyzx, -r0.xyzx
  add r2.w, r2.w, l(0.000002)
  sqrt r2.w, r2.w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  mul r3.x, r2.w, r2.w
  mul r2.w, r2.w, r3.x
  mul r2.w, r2.w, l(66.730003)
  itof r1.w, r1.w
  mul r1.w, r1.w, r2.w
  mad r1.xyz, -r0.xyzx, r1.wwww, r1.xyzx
  mad r2.xyz, r1.xyzx, cb0[1].xxxx, r2.xyzx
  mul r2.xyz, r2.xyzx, cb0[1].yyyy
  mad r0.xyz, r2.xyzx, cb0[1].xxxx, r0.xyzx
  store_structured u0.xyzw, vThreadID.x, l(0), r0.xyzw
  dp3 r0.x, r1.xyzx, r1.xyzx
  sqrt r2.w, r0.x
  store_structured u0.xyzw, vThreadID.x, l(16), r2.xyzw
endif 
ret 
// Approximately 1317 instruction slots used
