//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_4_0 /Fo ParticleDraw.o /Fc ParticleDraw.asm ParticleDraw.hlsl /E
//    VSParticleDraw
//
//
// Buffer Definitions: 
//
// Resource bind info for g_bufPosVelo
// {
//
//   struct
//   {
//       
//       float4 pos;                    // Offset:    0
//       float4 velo;                   // Offset:   16
//
//   } $Element;                        // Offset:    0 Size:    32
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_bufPosVelo                      texture  struct         r/o    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// COLOR                    0   xyzw        0     NONE  float   xyzw
// SV_VERTEXID              0   x           1   VERTID   uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyz         0     NONE  float   xyz 
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
vs_4_0
dcl_globalFlags refactoringAllowed | enableRawAndStructuredBuffers
dcl_resource_structured t0, 32 
dcl_input v0.xyzw
dcl_input_sgv v1.x, vertex_id
dcl_output o0.xyz
dcl_output o1.xyzw
dcl_temps 2
ld_structured o0.xyz, v1.x, l(0), t0.xyzx
ld_structured r0.x, v1.x, l(28), t0.xxxx
mul r0.x, r0.x, l(0.111111)
add r1.xyzw, v0.xyzw, l(-1.000000, -0.100000, -0.100000, -1.000000)
mad o1.xyzw, r0.xxxx, r1.xyzw, l(1.000000, 0.100000, 0.100000, 1.000000)
ret 
// Approximately 6 instruction slots used
