//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20714
//
//
///
// Buffer Definitions: 
//
// cbuffer cbCS
// {
//
//   uint g_tex_width;                  // Offset:    0 Size:     4
//   uint g_num_block_x;                // Offset:    4 Size:     4
//   uint g_format;                     // Offset:    8 Size:     4 [unused]
//   uint g_tex_size;                   // Offset:   12 Size:     4
//   uint g_start_block_id;             // Offset:   16 Size:     4
//
// }
//
// Resource bind info for g_InBuff
// {
//
//   uint4 $Element;                    // Offset:    0 Size:    16
//
// }
//
// Resource bind info for g_OutBuff
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_InBuff                          texture  struct         r/o    0        1
// g_OutBuff                             UAV  struct         r/w    0        1
// cbCS                              cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_4_0
dcl_globalFlags refactoringAllowed
dcl_immediateConstantBuffer { { 15, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 21},
                              { 15, 0, 0.000000, 43},
                              { 15, 0, 0.000000, 64},
                              { 15, 0, 0x00010105, 0},
                              { 15, 0, 0.000000, 9},
                              { 15, 0, 0.000000, 18},
                              { 15, 0, 0x00010515, 27},
                              { 15, 0, 261, 37},
                              { 15, 0, 0.000000, 46},
                              { 15, 0, 0x00011555, 55},
                              { 15, 0, 277, 64},
                              { 15, 0, 0.000000, 0},
                              { 15, 0, 0x00005555, 4},
                              { 15, 0, 0x00555555, 9},
                              { 15, 0, 85, 13},
                              { 15, 0, 0x00405455, 17},
                              { 2, 0, 0.000000, 21},
                              { 8, 0, 0x00004054, 26},
                              { 2, 0, 0.000000, 30},
                              { 2, 0, 0.000000, 34},
                              { 8, 0, 0x00405054, 38},
                              { 8, 0, 0x00004050, 43},
                              { 15, 0, 0.000000, 47},
                              { 2, 0, 0.000000, 51},
                              { 8, 0, 0x00404050, 55},
                              { 2, 0, 0.000000, 60},
                              { 2, 0, 0.000000, 64},
                              { 8, 0, 0.000000, 0},
                              { 8, 0, 0x00555500, 0},
                              { 2, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 15, 0, 0x00550055, 0},
                              { 6, 0, 0.000000, 0},
                              { 8, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 8, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 8, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 6, 0, 0x00141400, 0},
                              { 6, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 6, 0, 0x00041504, 0},
                              { 8, 0, 0x00105410, 0},
                              { 15, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 15, 0, 0x00550505, 0},
                              { 2, 0, 0.000000, 0},
                              { 2, 0, 0.000000, 0},
                              { 15, 0, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 3, 8, 0.000000, 0},
                              { 8, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 8, 15, 0x00005a5a, 0},
                              { 3, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 8, 15, 0.000000, 0},
                              { 8, 15, 0x000055aa, 0},
                              { 8, 15, 0x005555aa, 0},
                              { 6, 15, 0x0055aaaa, 0},
                              { 6, 15, 0.000000, 0},
                              { 6, 15, 0.000000, 0},
                              { 5, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 3, 8, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 3, 8, 0.000000, 0},
                              { 8, 15, 0x005a5a5a, 0},
                              { 3, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 3, 8, 0.000000, 0},
                              { 6, 15, 0x00051a1a, 0},
                              { 8, 10, 0x0050a4a4, 0},
                              { 3, 5, 0.000000, 0},
                              { 8, 15, 0.000000, 0},
                              { 6, 8, 0.000000, 0},
                              { 6, 10, 0x00146969, 0},
                              { 8, 15, 0.000000, 0},
                              { 5, 15, 0.000000, 0},
                              { 10, 15, 0.000000, 0},
                              { 8, 15, 0.000000, 0},
                              { 8, 15, 0x00025a6a, 0},
                              { 3, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 5, 10, 0.000000, 0},
                              { 6, 10, 0x0055aa00, 0},
                              { 8, 10, 0.000000, 0},
                              { 8, 9, 0.000000, 0},
                              { 10, 15, 0.000000, 0},
                              { 6, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 8, 15, 0x00009999, 0},
                              { 5, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 6, 15, 0.000000, 0},
                              { 6, 15, 0.000000, 0},
                              { 8, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 5, 15, 0.000000, 0},
                              { 5, 15, 0.000000, 0},
                              { 5, 15, 0.000000, 0},
                              { 8, 15, 0.000000, 0},
                              { 5, 15, 0.000000, 0},
                              { 10, 15, 0x00009696, 0},
                              { 5, 15, 0.000000, 0},
                              { 10, 15, 0.000000, 0},
                              { 8, 15, 0.000000, 0},
                              { 13, 15, 150, 0},
                              { 3, 15, 0.000000, 0},
                              { 12, 15, 0.000000, 0},
                              { 3, 15, 0.000000, 0},
                              { 3, 8, 0.000000, 0} }
dcl_constantbuffer cb0[2], immediateIndexed
dcl_resource_structured t0, 16 
dcl_uav_structured u0, 4
dcl_input vThreadIDInGroupFlattened
dcl_input vThreadGroupID.x
dcl_temps 9
dcl_tgsm_structured g0, 16, 64
dcl_thread_group 64, 1, 1
ushr r0.x, vThreadIDInGroupFlattened.x, l(4)
ishl r0.y, vThreadGroupID.x, l(2)
iadd r0.y, r0.y, cb0[1].x
iadd r0.x, r0.x, r0.y
and r0.y, vThreadIDInGroupFlattened.x, l(48)
iadd r0.z, -r0.y, vThreadIDInGroupFlattened.x
ieq r0.w, r0.z, l(1)
if_z r0.z
  ld_structured r1.xyzw, r0.x, l(0), t0.xyzw
  store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r1.xyzw
endif 
ld_structured r1.xyzw, r0.y, l(0), g0.xyzw
and r2.x, r1.x, l(1)
if_nz r2.x
  ushr r2.x, r1.x, l(1)
  and r2.x, r2.x, l(15)
  iadd r2.y, r2.x, l(64)
  mov r2.xz, l(0,0,0,0)
  mov r3.xy, l(3,0,0,0)
else 
  and r2.w, r1.x, l(2)
  if_nz r2.w
    ushr r2.w, r1.x, l(2)
    and r2.y, r2.w, l(63)
    mov r2.xz, l(1,0,0,0)
    mov r3.xy, l(3,0,0,0)
  else 
    and r2.w, r1.x, l(4)
    if_nz r2.w
      ushr r2.w, r1.x, l(3)
      and r2.w, r2.w, l(63)
      iadd r2.y, r2.w, l(64)
      mov r2.xz, l(2,0,0,0)
      mov r3.xy, l(2,0,0,0)
    else 
      ushr r4.x, r1.x, l(4)
      ushr r4.y, r1.x, l(5)
      ushr r4.z, r1.x, l(6)
      ushr r4.w, r1.x, l(8)
      and r5.xyzw, r1.xxxx, l(8, 16, 128, 32)
      movc r3.zw, r5.zzzz, l(0,0,3,2), l(0,0,2,3)
      and r2.w, r1.x, l(64)
      and r4.xyzw, r4.yxzw, l(3, 63, 3, 63)
      mov r6.xz, l(7,0,0,0)
      mov r6.y, r4.w
      movc r6.xyz, r2.wwww, l(6,0,0,0), r6.xyzx
      movc r2.w, r2.w, l(4), l(2)
      mov r7.xy, l(5,0,0,0)
      mov r7.z, r4.z
      movc r6.xyz, r5.wwww, r7.xyzx, r6.xyzx
      movc r2.w, r5.w, l(2), r2.w
      mov r7.xy, l(4,0,0,0)
      mov r7.z, r4.x
      movc r6.xyz, r5.yyyy, r7.xyzx, r6.xyzx
      movc r3.zw, r5.yyyy, r3.zzzw, r2.wwww
      mov r4.xz, l(3,0,0,0)
      movc r2.xyz, r5.xxxx, r4.xyzx, r6.xyzx
      movc r3.xy, r5.xxxx, l(2,0,0,0), r3.zwzz
    endif 
  endif 
endif 
if_nz r0.w
  if_z r2.x
    ushr r4.x, r1.x, l(1)
    ushr r4.y, r1.x, l(25)
    ushr r4.z, r1.y, l(17)
    ushr r4.w, r1.z, l(10)
    and r4.xyzw, r4.xyzw, l(240, 112, 240, 8)
    ishl r0.w, r1.y, l(7)
    and r0.w, r0.w, l(128)
    iadd r4.y, r0.w, r4.y
    ushr r5.xyz, r4.xyzx, l(5)
    iadd r5.xyz, r4.wwww, r5.xyzx
    iadd r4.xyz, r4.xyzx, r5.xyzx
    mov r4.w, l(255)
  else 
    ieq r0.w, r2.x, l(1)
    if_nz r0.w
      ushr r5.x, r1.x, l(6)
      ushr r5.y, r1.y, l(22)
      ushr r5.z, r1.z, l(15)
      ishl r0.w, r1.y, l(2)
      and r6.w, r0.w, l(252)
      and r6.xyz, r5.xyzx, l(252, 252, 2, 0)
      ushr r5.xyz, r6.xwyx, l(7)
      iadd r5.xyz, r5.xyzx, r6.zzzz
      iadd r4.xyz, r5.xyzx, r6.xwyx
      mov r4.w, l(255)
    else 
      ieq r0.w, r2.x, l(2)
      if_nz r0.w
        ushr r5.x, r1.x, l(6)
        ushr r5.y, r1.y, l(4)
        ushr r5.z, r1.z, l(2)
        and r5.xyz, r5.xyzx, l(248, 248, 248, 0)
        ushr r6.xyz, r5.xyzx, l(5)
        iadd r4.xyz, r5.xyzx, r6.xyzx
        mov r4.w, l(255)
      else 
        ieq r0.w, r2.x, l(3)
        if_nz r0.w
          ushr r5.x, r1.x, l(9)
          ushr r5.y, r1.y, l(5)
          ushr r5.z, r1.z, l(1)
          ushr r5.w, r1.z, l(30)
          and r5.xyzw, r5.xyzw, l(254, 254, 254, 1)
          iadd r4.xyz, r5.wwww, r5.xyzx
          mov r4.w, l(255)
        else 
          ieq r0.w, r2.x, l(4)
          if_nz r0.w
            ushr r5.x, r1.x, l(5)
            ushr r5.y, r1.x, l(15)
            ushr r5.z, r1.x, l(25)
            ushr r5.w, r1.y, l(4)
            and r5.xyzw, r5.xyzw, l(248, 248, 120, 252)
            ishl r0.w, r1.y, l(7)
            and r0.w, r0.w, l(128)
            iadd r5.z, r0.w, r5.z
            ushr r6.xyz, r5.xyzx, l(5)
            iadd r4.xyz, r5.xyzx, r6.xyzx
            ushr r0.w, r5.w, l(6)
            iadd r4.w, r0.w, r5.w
          else 
            ushr r5.x, r1.x, l(7)
            ushr r5.y, r1.x, l(21)
            ushr r5.z, r1.y, l(3)
            ushr r5.w, r1.y, l(18)
            and r5.xyzw, r5.xyzw, l(254, 254, 254, 255)
            ushr r6.xyz, r5.xyzx, l(7)
            iadd r5.xyz, r5.xyzx, r6.xyzx
            ieq r3.zw, r2.xxxx, l(0, 0, 5, 6)
            ushr r6.x, r1.x, l(6)
            ushr r6.y, r1.x, l(20)
            ushr r6.z, r1.y, l(2)
            ushr r6.w, r1.y, l(16)
            and r6.xyzw, r6.xyzw, l(254, 254, 254, 254)
            ushr r7.x, r1.y, l(31)
            ushr r7.y, r1.x, l(11)
            ushr r7.z, r1.y, l(19)
            ushr r7.w, r1.z, l(7)
            iadd r6.xyzw, r6.xyzw, r7.xxxx
            ishl r0.w, r1.y, l(1)
            and r8.y, r0.w, l(248)
            and r8.xzw, r7.yyzw, l(248, 0, 248, 248)
            ushr r0.w, r1.z, l(28)
            and r0.w, r0.w, l(4)
            ushr r7.xyzw, r8.xyzw, l(6)
            iadd r7.xyzw, r0.wwww, r7.xyzw
            iadd r7.xyzw, r7.xyzw, r8.xyzw
            movc r6.xyzw, r3.wwww, r6.xyzw, r7.xyzw
            movc r4.xyzw, r3.zzzz, r5.xyzw, r6.xyzw
          endif 
        endif 
      endif 
    endif 
  endif 
  store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r4.xyzw
else 
  ieq r0.w, r0.z, l(2)
  if_nz r0.w
    if_z r2.x
      ushr r4.x, r1.x, l(5)
      ushr r4.y, r1.y, l(21)
      ushr r4.z, r1.z, l(11)
      ishl r0.w, r1.y, l(3)
      and r5.w, r0.w, l(240)
      and r5.xyz, r4.xyzx, l(240, 240, 8, 0)
      ushr r4.xyz, r5.xwyx, l(5)
      iadd r4.xyz, r4.xyzx, r5.zzzz
      iadd r4.xyz, r4.xyzx, r5.xwyx
      mov r4.w, l(255)
    else 
      ieq r0.w, r2.x, l(1)
      if_nz r0.w
        ushr r5.x, r1.x, l(12)
        ushr r5.y, r1.y, l(4)
        ushr r5.z, r1.y, l(28)
        ushr r5.w, r1.z, l(15)
        and r5.xyzw, r5.xyzw, l(252, 252, 12, 2)
        ishl r0.w, r1.z, l(4)
        and r0.w, r0.w, l(240)
        iadd r5.z, r0.w, r5.z
        ushr r6.xyz, r5.xyzx, l(7)
        iadd r6.xyz, r5.wwww, r6.xyzx
        iadd r4.xyz, r5.xyzx, r6.xyzx
        mov r4.w, l(255)
      else 
        ieq r0.w, r2.x, l(2)
        if_nz r0.w
          ushr r5.x, r1.x, l(11)
          ushr r5.y, r1.y, l(9)
          ushr r5.z, r1.z, l(7)
          and r5.xyz, r5.xyzx, l(248, 248, 248, 0)
          ushr r6.xyz, r5.xyzx, l(5)
          iadd r4.xyz, r5.xyzx, r6.xyzx
          mov r4.w, l(255)
        else 
          ieq r0.w, r2.x, l(3)
          if_nz r0.w
            ushr r5.x, r1.x, l(16)
            ushr r5.y, r1.y, l(12)
            ushr r5.z, r1.z, l(8)
            ushr r0.w, r1.z, l(31)
            and r5.xyz, r5.xyzx, l(254, 254, 254, 0)
            iadd r4.xyz, r0.wwww, r5.xyzx
            mov r4.w, l(255)
          else 
            ieq r0.w, r2.x, l(4)
            if_nz r0.w
              ushr r5.xz, r1.xxyx, l(10)
              ushr r5.y, r1.x, l(20)
              ishl r0.w, r1.y, l(2)
              and r6.w, r0.w, l(248)
              and r6.xyz, r5.xyzx, l(248, 248, 252, 0)
              ushr r5.xyz, r6.xywx, l(5)
              ushr r5.w, r6.z, l(6)
              iadd r4.xyzw, r5.xyzw, r6.xywz
            else 
              ieq r0.w, r2.x, l(5)
              if_nz r0.w
                ushr r5.x, r1.x, l(14)
                ushr r5.y, r1.x, l(28)
                ushr r5.z, r1.y, l(10)
                ushr r0.w, r1.y, l(26)
                and r5.xyz, r5.xyzx, l(254, 14, 254, 0)
                ishl r6.x, r1.y, l(4)
                ishl r6.y, r1.z, l(6)
                and r3.zw, r6.xxxy, l(0, 0, 240, 192)
                iadd r5.w, r3.z, r5.y
                iadd r4.w, r0.w, r3.w
                ushr r6.xyz, r5.xwzx, l(7)
                iadd r4.xyz, r5.xwzx, r6.xyzx
              else 
                ieq r0.w, r2.x, l(6)
                ushr r5.x, r1.x, l(13)
                ushr r5.y, r1.x, l(27)
                ushr r5.z, r1.y, l(9)
                ushr r5.w, r1.y, l(23)
                and r5.xyzw, r5.xyzw, l(254, 30, 254, 254)
                ishl r2.w, r1.y, l(5)
                and r2.w, r2.w, l(224)
                iadd r5.y, r2.w, r5.y
                and r2.w, r1.z, l(1)
                iadd r5.xyzw, r2.wwww, r5.xyzw
                ushr r6.x, r1.x, l(16)
                ushr r6.y, r1.y, l(4)
                ushr r6.z, r1.y, l(24)
                ushr r6.w, r1.z, l(12)
                and r6.xyzw, r6.xyzw, l(248, 248, 248, 248)
                ushr r2.w, r1.z, l(29)
                and r2.w, r2.w, l(4)
                ushr r7.xyzw, r6.xyzw, l(6)
                iadd r7.xyzw, r2.wwww, r7.xyzw
                iadd r6.xyzw, r6.xyzw, r7.xyzw
                movc r4.xyzw, r0.wwww, r5.xyzw, r6.xyzw
              endif 
            endif 
          endif 
        endif 
      endif 
    endif 
    store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r4.xyzw
  else 
    ieq r0.w, r0.z, l(3)
    if_nz r0.w
      if_z r2.x
        ushr r4.x, r1.x, l(9)
        ushr r4.y, r1.y, l(1)
        ushr r4.z, r1.y, l(25)
        ushr r4.w, r1.z, l(12)
        and r4.xyzw, r4.xyzw, l(240, 240, 112, 8)
        ishl r0.w, r1.z, l(7)
        and r0.w, r0.w, l(128)
        iadd r4.z, r0.w, r4.z
        ushr r5.xyz, r4.xyzx, l(5)
        iadd r5.xyz, r4.wwww, r5.xyzx
        iadd r4.xyz, r4.xyzx, r5.xyzx
        mov r4.w, l(255)
      else 
        ieq r0.w, r2.x, l(1)
        if_nz r0.w
          ushr r5.x, r1.x, l(18)
          ushr r5.y, r1.y, l(10)
          ushr r5.z, r1.z, l(2)
          ushr r5.w, r1.z, l(16)
          and r5.xyzw, r5.xyzw, l(252, 252, 252, 2)
          ushr r6.xyz, r5.xyzx, l(7)
          iadd r6.xyz, r5.wwww, r6.xyzx
          iadd r4.xyz, r5.xyzx, r6.xyzx
          mov r4.w, l(255)
        else 
          ieq r0.w, r2.x, l(2)
          if_nz r0.w
            ushr r5.x, r1.x, l(16)
            ushr r5.y, r1.y, l(14)
            ushr r5.z, r1.z, l(12)
            and r5.xyz, r5.xyzx, l(248, 248, 248, 0)
            ushr r6.xyz, r5.xyzx, l(5)
            iadd r4.xyz, r5.xyzx, r6.xyzx
            mov r4.w, l(255)
          else 
            ieq r0.w, r2.x, l(3)
            if_nz r0.w
              ushr r5.x, r1.x, l(23)
              ushr r5.y, r1.y, l(19)
              ushr r5.z, r1.z, l(15)
              and r5.xyz, r5.xyzx, l(254, 254, 254, 0)
              and r0.w, r1.w, l(1)
              iadd r4.xyz, r0.wwww, r5.xyzx
              mov r4.w, l(255)
            else 
              ieq r5.xyz, r2.xxxx, l(4, 5, 6, 0)
              ushr r6.x, r1.x, l(21)
              ushr r6.y, r1.y, l(9)
              ushr r6.w, r1.z, l(17)
              ishl r7.x, r1.z, l(3)
              ishl r7.y, r1.w, l(2)
              and r6.xyw, r6.xyxw, l(248, 248, 0, 248)
              and r3.zw, r7.xxxy, l(0, 0, 248, 4)
              mov r6.z, r3.z
              ushr r7.xyzw, r6.xyzw, l(6)
              iadd r7.xyzw, r3.wwww, r7.xyzw
              iadd r6.xyzw, r6.xyzw, r7.xyzw
              or r0.w, r5.y, r5.z
              or r0.w, r5.x, r0.w
              movc r4.xyzw, r0.wwww, l(0,0,0,0), r6.xyzw
            endif 
          endif 
        endif 
      endif 
      store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r4.xyzw
    else 
      ieq r0.w, r0.z, l(4)
      if_nz r0.w
        if_z r2.x
          ushr r4.xz, r1.xxzx, l(13)
          ushr r4.y, r1.y, l(5)
          ishl r0.w, r1.z, l(3)
          and r5.w, r0.w, l(240)
          and r5.xyz, r4.xyzx, l(240, 240, 8, 0)
          ushr r4.xyz, r5.xywx, l(5)
          iadd r4.xyz, r4.xyzx, r5.zzzz
          iadd r4.xyz, r4.xyzx, r5.xywx
          mov r4.w, l(255)
        else 
          ieq r0.w, r2.x, l(1)
          if_nz r0.w
            ushr r5.x, r1.x, l(24)
            ushr r5.yw, r1.yyyz, l(16)
            ushr r5.z, r1.z, l(8)
            and r5.xyzw, r5.xyzw, l(252, 252, 252, 2)
            ushr r6.xyz, r5.xyzx, l(7)
            iadd r6.xyz, r5.wwww, r6.xyzx
            iadd r4.xyz, r5.xyzx, r6.xyzx
            mov r4.w, l(255)
          else 
            ieq r0.w, r2.x, l(2)
            if_nz r0.w
              ushr r5.x, r1.x, l(21)
              ushr r5.y, r1.y, l(19)
              ushr r5.z, r1.z, l(17)
              and r5.xyz, r5.xyzx, l(248, 248, 248, 0)
              ushr r6.xyz, r5.xyzx, l(5)
              iadd r4.xyz, r5.xyzx, r6.xyzx
              mov r4.w, l(255)
            else 
              ieq r0.w, r2.x, l(3)
              if_nz r0.w
                ushr r5.x, r1.x, l(30)
                ushr r5.y, r1.y, l(26)
                ushr r5.z, r1.z, l(22)
                ushr r5.w, r1.w, l(1)
                and r5.xyzw, r5.xyzw, l(2, 62, 254, 1)
                ishl r6.x, r1.y, l(2)
                ishl r6.y, r1.z, l(6)
                and r3.zw, r6.xxxy, l(0, 0, 252, 192)
                iadd r5.xy, r3.zwzz, r5.xyxx
                iadd r4.xyz, r5.wwww, r5.xyzx
                mov r4.w, l(255)
              else 
                ieq r5.xyz, r2.xxxx, l(4, 5, 6, 0)
                ushr r6.x, r1.x, l(26)
                ushr r6.y, r1.y, l(14)
                ushr r6.z, r1.z, l(2)
                ushr r6.w, r1.z, l(22)
                and r6.xyzw, r6.xyzw, l(56, 248, 248, 248)
                ishl r7.x, r1.y, l(6)
                ishl r7.y, r1.w, l(1)
                and r3.zw, r7.xxxy, l(0, 0, 192, 4)
                iadd r6.x, r3.z, r6.x
                ushr r7.xyzw, r6.xyzw, l(6)
                iadd r7.xyzw, r3.wwww, r7.xyzw
                iadd r6.xyzw, r6.xyzw, r7.xyzw
                or r0.w, r5.y, r5.z
                or r0.w, r5.x, r0.w
                movc r4.xyzw, r0.wwww, l(0,0,0,0), r6.xyzw
              endif 
            endif 
          endif 
        endif 
        store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r4.xyzw
      else 
        ieq r0.w, r0.z, l(5)
        if_nz r0.w
          if_z r2.x
            ushr r4.x, r1.x, l(17)
            ushr r4.y, r1.y, l(9)
            ushr r4.z, r1.z, l(1)
            ushr r4.w, r1.z, l(14)
            and r4.xyzw, r4.xyzw, l(240, 240, 240, 8)
            ushr r5.xyz, r4.xyzx, l(5)
            iadd r5.xyz, r4.wwww, r5.xyzx
            iadd r4.xyz, r4.xyzx, r5.xyzx
            mov r4.w, l(255)
          else 
            ieq r0.w, r2.x, l(1)
            if_nz r0.w
              mov r4.xyzw, l(0,0,0,0)
            else 
              ieq r0.w, r2.x, l(2)
              if_nz r0.w
                ushr r5.x, r1.x, l(26)
                ushr r5.y, r1.y, l(24)
                ushr r5.z, r1.z, l(22)
                and r5.xyz, r5.xyzx, l(56, 248, 248, 0)
                ishl r0.w, r1.y, l(6)
                and r0.w, r0.w, l(192)
                iadd r5.x, r0.w, r5.x
                mov r5.w, l(255)
                ushr r6.xyzw, r5.xyzw, l(5)
                or r4.xyzw, r5.xyzw, r6.xyzw
              else 
                mov r4.xyzw, l(0,0,0,0)
              endif 
            endif 
          endif 
          store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r4.xyzw
        else 
          ieq r0.w, r0.z, l(6)
          if_nz r0.w
            if_z r2.x
              ushr r4.x, r1.x, l(21)
              ushr r4.y, r1.y, l(13)
              ushr r4.z, r1.z, l(5)
              ushr r4.w, r1.z, l(15)
              and r4.xyzw, r4.xyzw, l(240, 240, 240, 8)
              ushr r5.xyz, r4.xyzx, l(5)
              iadd r5.xyz, r4.wwww, r5.xyzx
              iadd r4.xyz, r4.xyzx, r5.xyzx
              mov r4.w, l(255)
            else 
              ieq r0.w, r2.x, l(1)
              if_nz r0.w
                mov r4.xyzw, l(0,0,0,0)
              else 
                ieq r0.w, r2.x, l(2)
                if_nz r0.w
                  ishl r5.x, r1.y, l(1)
                  ishl r5.y, r1.z, l(3)
                  ishl r5.z, r1.w, l(5)
                  ushr r0.w, r1.z, l(27)
                  and r0.w, r0.w, l(24)
                  and r5.xyz, r5.xyzx, l(248, 248, 224, 0)
                  iadd r5.z, r0.w, r5.z
                  mov r5.w, l(255)
                  ushr r6.xyzw, r5.xyzw, l(5)
                  or r4.xyzw, r5.xyzw, r6.xyzw
                else 
                  mov r4.xyzw, l(0,0,0,0)
                endif 
              endif 
            endif 
            store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r4.xyzw
          endif 
        endif 
      endif 
    endif 
  endif 
endif 
ushr r0.w, r0.z, l(2)
and r2.w, r0.z, l(-4)
iadd r2.w, r0.z, -r2.w
udiv r3.z, null, r0.x, cb0[0].y
imad r0.x, -r3.z, cb0[0].y, r0.x
ishl r3.z, r3.z, l(2)
iadd r0.w, r0.w, r3.z
ishl r0.x, r0.x, l(2)
imad r0.x, r0.w, cb0[0].x, r0.x
iadd r0.x, r2.w, r0.x
ult r0.w, r0.x, cb0[0].w
if_nz r0.w
  if_z r2.x
    if_z r0.z
      ushr r0.w, r1.z, l(19)
      and r3.w, r0.w, l(3)
    else 
      ult r0.w, r0.z, icb[r2.y + 0].x
      if_nz r0.w
        ult r0.w, r0.z, l(4)
        imad r4.xyz, r0.zzzz, l(3, 3, 3, 0), l(18, 18, -14, 0)
        ushr r5.x, r1.z, r4.x
        ushr r5.y, r1.z, r4.y
        ushr r5.z, r1.w, r4.z
        ieq r2.w, r0.z, l(4)
        and r4.xyz, r5.xyzx, l(7, 3, 7, 0)
        ishl r4.w, r1.w, l(2)
        and r4.w, r4.w, l(4)
        iadd r4.y, r4.w, r4.y
        movc r2.w, r2.w, r4.y, r4.z
        movc r3.w, r0.w, r4.x, r2.w
      else 
        ieq r0.w, r0.z, icb[r2.y + 0].x
        if_nz r0.w
          uge r0.w, l(4), r0.z
          imad r4.xy, r0.zzzz, l(3, 3, 0, 0), l(18, -14, 0, 0)
          ushr r5.x, r1.z, r4.x
          ushr r5.y, r1.w, r4.y
          and r4.xy, r5.xyxx, l(3, 3, 0, 0)
          movc r3.w, r0.w, r4.x, r4.y
        else 
          ult r0.w, r0.z, icb[r2.y + 0].y
          if_nz r0.w
            uge r0.w, l(4), r0.z
            imad r4.xy, r0.zzzz, l(3, 3, 0, 0), l(17, -15, 0, 0)
            ushr r5.x, r1.z, r4.x
            ushr r5.y, r1.w, r4.y
            and r4.xy, r5.xyxx, l(7, 7, 0, 0)
            movc r3.w, r0.w, r4.x, r4.y
          else 
            ieq r0.w, r0.z, icb[r2.y + 0].y
            imad r4.xy, r0.zzzz, l(3, 3, 0, 0), l(-15, -16, 0, 0)
            ushr r5.x, r1.w, r4.x
            ushr r5.y, r1.w, r4.y
            and r4.xy, r5.xyxx, l(3, 7, 0, 0)
            movc r3.w, r0.w, r4.x, r4.y
          endif 
        endif 
      endif 
    endif 
    ishl r0.w, r0.z, l(1)
    iadd r0.w, -r0.w, l(30)
    ushr r0.w, icb[r2.y + 0].z, r0.w
    and r0.w, r0.w, l(3)
    mov r3.z, l(0)
  else 
    ieq r2.w, r2.x, l(1)
    if_nz r2.w
      if_z r0.z
        ushr r2.w, r1.z, l(18)
        and r3.w, r2.w, l(3)
      else 
        ult r2.w, r0.z, icb[r2.y + 0].x
        if_nz r2.w
          ult r2.w, r0.z, l(5)
          imad r4.xy, r0.zzzz, l(3, 3, 0, 0), l(17, -15, 0, 0)
          ushr r5.x, r1.z, r4.x
          ushr r5.y, r1.w, r4.y
          and r4.xy, r5.xyxx, l(7, 7, 0, 0)
          movc r3.w, r2.w, r4.x, r4.y
        else 
          ieq r2.w, r0.z, icb[r2.y + 0].x
          ult r4.x, r0.z, l(5)
          imad r5.xyzw, r0.zzzz, l(3, 3, 3, 3), l(17, -15, 16, -16)
          ushr r6.x, r1.z, r5.x
          ushr r6.y, r1.w, r5.y
          ushr r6.z, r1.z, r5.z
          ushr r4.y, r1.w, r5.w
          and r5.xyzw, r6.xyzz, l(3, 3, 7, 1)
          movc r4.z, r4.x, r5.x, r5.y
          ieq r4.w, r0.z, l(5)
          ishl r5.x, r1.w, l(1)
          and r5.x, r5.x, l(6)
          iadd r5.x, r5.x, r5.w
          and r4.y, r4.y, l(7)
          movc r4.y, r4.w, r5.x, r4.y
          movc r4.x, r4.x, r5.z, r4.y
          movc r3.w, r2.w, r4.z, r4.x
        endif 
      endif 
      ishl r2.w, r0.z, l(1)
      iadd r2.w, -r2.w, l(30)
      ushr r2.w, icb[r2.y + 0].z, r2.w
      and r0.w, r2.w, l(3)
      mov r3.z, l(0)
    else 
      ieq r2.w, r2.x, l(2)
      if_nz r2.w
        if_z r0.z
          ushr r2.w, r1.w, l(3)
          and r3.w, r2.w, l(1)
        else 
          ult r2.w, r0.z, icb[r2.y + 0].x
          if_nz r2.w
            ishl r2.w, r0.z, l(1)
            iadd r2.w, r2.w, l(2)
            ushr r2.w, r1.w, r2.w
            and r3.w, r2.w, l(3)
          else 
            ieq r2.w, r0.z, icb[r2.y + 0].x
            if_nz r2.w
              ishl r2.w, r0.z, l(1)
              iadd r2.w, r2.w, l(2)
              ushr r2.w, r1.w, r2.w
              and r3.w, r2.w, l(1)
            else 
              ult r2.w, r0.z, icb[r2.y + 0].y
              if_nz r2.w
                ishl r2.w, r0.z, l(1)
                iadd r2.w, r2.w, l(1)
                ushr r2.w, r1.w, r2.w
                and r3.w, r2.w, l(3)
              else 
                ieq r2.w, r0.z, icb[r2.y + 0].y
                ishl r4.x, r0.z, l(1)
                iadd r4.y, r4.x, l(1)
                ushr r4.y, r1.w, r4.y
                ushr r4.x, r1.w, r4.x
                and r4.xy, r4.xyxx, l(3, 1, 0, 0)
                movc r3.w, r2.w, r4.y, r4.x
              endif 
            endif 
          endif 
        endif 
        ishl r2.w, r0.z, l(1)
        iadd r2.w, -r2.w, l(30)
        ushr r2.w, icb[r2.y + 0].z, r2.w
        and r0.w, r2.w, l(3)
        mov r3.z, l(0)
      else 
        ieq r2.w, r2.x, l(3)
        if_nz r2.w
          if_z r0.z
            ushr r2.w, r1.w, l(2)
            and r3.w, r2.w, l(1)
          else 
            ult r2.w, r0.z, icb[r2.y + 0].x
            if_nz r2.w
              ishl r2.w, r0.z, l(1)
              iadd r2.w, r2.w, l(1)
              ushr r2.w, r1.w, r2.w
              and r3.w, r2.w, l(3)
            else 
              ieq r2.w, r0.z, icb[r2.y + 0].x
              ishl r4.x, r0.z, l(1)
              iadd r4.y, r4.x, l(1)
              ushr r4.y, r1.w, r4.y
              ushr r4.x, r1.w, r4.x
              and r4.xy, r4.xyxx, l(3, 1, 0, 0)
              movc r3.w, r2.w, r4.y, r4.x
            endif 
          endif 
          ishl r2.w, r0.z, l(1)
          iadd r2.w, -r2.w, l(30)
          ushr r2.w, icb[r2.y + 0].z, r2.w
          and r0.w, r2.w, l(3)
          mov r3.z, l(0)
        else 
          ieq r2.w, r2.x, l(4)
          if_nz r2.w
            ushr r4.x, r1.y, l(18)
            ushr r4.y, r1.z, l(17)
            and r4.xy, r4.xyxx, l(1, 3, 0, 0)
            ult r4.zw, r0.zzzz, l(0, 0, 7, 5)
            ishl r2.w, r0.z, l(1)
            iadd r5.xyz, r2.wwww, l(17, 17, -15, 0)
            ushr r6.x, r1.y, r5.x
            ushr r6.y, r1.y, r5.y
            ushr r6.z, r1.z, r5.z
            ieq r5.xy, r0.zzzz, l(7, 5, 0, 0)
            and r6.xyz, r6.xyzx, l(3, 1, 3, 0)
            ishl r5.zw, r1.zzzw, l(1)
            and r5.zw, r5.zzzw, l(0, 0, 2, 6)
            iadd r1.y, r5.z, r6.y
            movc r1.y, r5.x, r1.y, r6.z
            movc r1.y, r4.z, r6.x, r1.y
            movc r6.x, r0.z, r1.y, r4.x
            imad r7.xyz, r0.zzzz, l(3, 3, 3, 0), l(16, 16, -16, 0)
            ushr r8.x, r1.z, r7.x
            ushr r8.y, r1.z, r7.y
            ushr r8.z, r1.w, r7.z
            and r7.xyz, r8.xyzx, l(7, 1, 7, 0)
            iadd r1.y, r5.w, r7.y
            movc r1.y, r5.y, r1.y, r7.z
            movc r1.y, r4.w, r7.x, r1.y
            movc r6.y, r0.z, r1.y, r4.y
            and r1.x, r1.x, l(128)
            movc r3.zw, r1.xxxx, r6.xxxy, r6.yyyx
            mov r0.w, l(0)
          else 
            ieq r1.x, r2.x, l(5)
            if_nz r1.x
              ushr r4.x, r1.z, l(2)
              ushr r1.x, r1.z, l(31)
              ushr r4.z, r1.w, l(1)
              and r4.xy, r4.xzxx, l(1, 1, 0, 0)
              ult r1.y, r0.z, l(15)
              ishl r2.w, r0.z, l(1)
              iadd r4.z, r2.w, l(1)
              ushr r4.z, r1.z, r4.z
              ishl r4.w, r1.w, l(1)
              and r4.zw, r4.zzzw, l(0, 0, 3, 2)
              iadd r1.x, r1.x, r4.w
              movc r1.x, r1.y, r4.z, r1.x
              movc r3.w, r0.z, r1.x, r4.x
              ushr r1.x, r1.w, r2.w
              and r1.x, r1.x, l(3)
              movc r3.z, r0.z, r1.x, r4.y
              mov r0.w, l(0)
            else 
              ieq r1.x, r2.x, l(6)
              if_nz r1.x
                ushr r1.x, r1.z, l(1)
                ult r1.y, r0.z, l(8)
                ishl r2.w, r0.z, l(2)
                ushr r1.z, r1.z, r2.w
                and r1.xz, r1.xxzx, l(7, 0, 15, 0)
                iadd r2.w, r2.w, l(-32)
                ushr r2.w, r1.w, r2.w
                and r2.w, r2.w, l(15)
                movc r1.y, r1.y, r1.z, r2.w
                movc r3.w, r0.z, r1.y, r1.x
                mov r3.z, r3.w
                mov r0.w, l(0)
              else 
                if_z r0.z
                  ushr r1.x, r1.w, l(2)
                  and r3.w, r1.x, l(1)
                else 
                  ult r1.x, r0.z, icb[r2.y + 0].x
                  if_nz r1.x
                    ishl r1.x, r0.z, l(1)
                    iadd r1.x, r1.x, l(1)
                    ushr r1.x, r1.w, r1.x
                    and r3.w, r1.x, l(3)
                  else 
                    ieq r1.x, r0.z, icb[r2.y + 0].x
                    ishl r1.y, r0.z, l(1)
                    iadd r1.z, r1.y, l(1)
                    ushr r1.z, r1.w, r1.z
                    ushr r1.y, r1.w, r1.y
                    and r1.yz, r1.yyzy, l(0, 3, 1, 0)
                    movc r3.w, r1.x, r1.z, r1.y
                  endif 
                endif 
                ishl r0.z, r0.z, l(1)
                iadd r0.z, -r0.z, l(30)
                ushr r0.z, icb[r2.y + 0].z, r0.z
                and r0.w, r0.z, l(3)
                mov r3.z, r3.w
              endif 
            endif 
          endif 
        endif 
      endif 
    endif 
  endif 
  ishl r0.z, r0.w, l(1)
  iadd r0.y, r0.z, r0.y
  iadd r0.z, r0.y, l(1)
  ld_structured r1.xyzw, r0.z, l(0), g0.xyzw
  iadd r0.y, r0.y, l(2)
  ld_structured r4.xyzw, r0.y, l(0), g0.xyzw
  ieq r0.y, r3.x, l(2)
  if_nz r0.y
    iadd r0.z, l(64), -icb[r3.w + 0].w
    imul null, r5.xyz, r4.xyzx, icb[r3.w + 0].wwww
    imad r5.xyz, r0.zzzz, r1.xyzx, r5.xyzx
    iadd r5.xyz, r5.xyzx, l(32, 32, 32, 0)
    ushr r5.yzw, r5.xxyz, l(6)
  endif 
  if_z r0.y
    ieq r0.y, r3.x, l(3)
    if_nz r0.y
      iadd r0.z, l(64), -icb[r3.w + 4].w
      imul null, r6.xyz, r4.xyzx, icb[r3.w + 4].wwww
      imad r6.xyz, r0.zzzz, r1.xyzx, r6.xyzx
      iadd r6.xyz, r6.xyzx, l(32, 32, 32, 0)
      ushr r5.yzw, r6.xxyz, l(6)
    endif 
    if_z r0.y
      iadd r0.y, l(64), -icb[r3.w + 12].w
      imul null, r4.xyz, r4.xyzx, icb[r3.w + 12].wwww
      imad r0.yzw, r0.yyyy, r1.xxyz, r4.xxyz
      iadd r0.yzw, r0.yyzw, l(0, 32, 32, 32)
      ushr r5.yzw, r0.yyzw, l(6)
    endif 
  endif 
  uge r0.y, r2.x, l(4)
  if_nz r0.y
    ieq r0.y, r3.y, l(2)
    if_nz r0.y
      iadd r0.z, l(64), -icb[r3.z + 0].w
      imul null, r0.w, r4.w, icb[r3.z + 0].w
      imad r0.z, r0.z, r1.w, r0.w
      iadd r0.z, r0.z, l(32)
      ushr r5.x, r0.z, l(6)
    endif 
    if_z r0.y
      ieq r0.y, r3.y, l(3)
      if_nz r0.y
        iadd r0.z, l(64), -icb[r3.z + 4].w
        imul null, r0.w, r4.w, icb[r3.z + 4].w
        imad r0.z, r0.z, r1.w, r0.w
        iadd r0.z, r0.z, l(32)
        ushr r5.x, r0.z, l(6)
      endif 
      if_z r0.y
        iadd r0.y, l(64), -icb[r3.z + 12].w
        imul null, r0.z, r4.w, icb[r3.z + 12].w
        imad r0.y, r0.y, r1.w, r0.z
        iadd r0.y, r0.y, l(32)
        ushr r5.x, r0.y, l(6)
      endif 
    endif 
  else 
    mov r5.x, l(255)
  endif 
  ieq r0.yzw, r2.zzzz, l(0, 1, 2, 3)
  movc r1.zw, r0.wwww, r5.xxxw, r5.wwwx
  mov r1.xy, r5.yzyy
  movc r1.yzw, r0.zzzz, r5.xxwz, r1.yyzw
  movc r1.xyzw, r0.yyyy, r5.xzwy, r1.xyzw
  ishl r0.y, r1.y, l(8)
  ishl r0.z, r1.z, l(16)
  ishl r0.w, r1.w, l(24)
  or r0.y, r0.y, r1.x
  or r0.y, r0.z, r0.y
  or r0.y, r0.w, r0.y
  store_structured u0.x, r0.x, l(0), r0.y
endif 
ret 
// Approximately 832 instruction slots used
